package readenv

const (
	// PREFIX for ENV Variables
	ENV_VAR_PREFIX = "ABCD"
	// ENV FILE FOR LOGS
	LOG_VAR_ENV_FILENAME = ".env"
	// Logging Variables
	LOG_CONSOLE_ENABLED = "LOG_CONSOLE_ENABLED"
	// Logging Variables
	CWD_VAR_LOG_LEVEL           = "LOG_LEVEL"
	CWD_VAR_LOG_FILE_ENABLED    = "LOG_FILE_ENABLED"
	CWD_VAR_LOG_FILE_LOCATION   = "LOG_FILE_LOC"
	CWD_VAR_LOG_CONSOLE_ENABLED = "LOG_CONSOLE_ENABLED"

	// ENV FILE FOR DBCOM
	DBCOMM_VAR_ENV_FILENAME = "DB_COMM.env"
	// Variable Names for DB
	DBCOM_VAR_SERVER_COUNT       = "DB_SERVER_COUNT"
	DBCOM_VAR_SERVER_HOST_COUNT  = "DB_HOST_"
	DBCOM_VAR_SERVER_PORT_COUNT  = "DB_PORT_"
	DBCOM_VAR_DB_NAME            = "DB_NAME"
	DBCOM_VAR_DB_USERNAME        = "DB_USERNAME"
	DBCOM_VAR_DB_PASSWORD        = "DB_PASSWORD"
	DBCOM_VAR_DB_DROP_TABLES     = "DB_DROP_TABLES"
	DBCOM_VAR_DB_LOG_LEVEL       = "DB_LOG_LEVEL"
	DBCOM_VAR_DB_CLEANUP_ENABLED = "DB_CLEANUP_ENABLED"
	// ENV FILE FOR REST
	REST_VAR_ENV_FILENAME = "REST.env"
	// Variable Names for REST
	GIN_VAR_REST_WEB_JWT_PASSKEY      = "GIN_REST_WEB_JWT_PASSKEY"
	GIN_VAR_REST_BASE_PATH            = "GIN_REST_API_BASE_PATH"
	GIN_VAR_REST_SERVER_EXTERNAL_PORT = "GIN_REST_SERVER_EXTERNAL_PORT"
)
